-- Comprehensive Flashcard Expansion
-- 450+ cards covering Industrial Automation with detailed explanations
-- Including tables, point-form descriptions, and structured content
-- Created: 2026-05-30

-- Insert comprehensive flashcards for all major topics
-- These cards are extracted from exam revision guides with proper formatting

INSERT INTO public.cards (topic_set_id, order_index, question, answer) VALUES

-- HMI AND INTERFACE CARDS
('11111111-1111-1111-1111-111111111111', 26, 'What is an HMI (Human Machine Interface)?', 'A user interface connecting an operator to a machine, system, or device. Displays real-time process data (temperatures, pressures, motor status). Allows operators to send commands (start/stop, setpoints) via touch screen. Logs alarms, trends, and events. Enables monitoring and control through communication protocols.'),

('11111111-1111-1111-1111-111111111111', 27, 'State the five parameters involved when backing up HMI data.', '1. Screen layouts and graphics (all display pages, buttons, indicators, navigation links) 2. Tag database (variable definitions linking HMI to PLC memory) 3. Alarm configuration (messages, conditions, priorities, acknowledgment) 4. Recipes and data logs (production recipes, historical trend data) 5. User accounts and security (names, passwords, access levels, audit trails)'),

('11111111-1111-1111-1111-111111111111', 28, 'What are three benefits of backing up HMI data?', '• Disaster recovery - Restore system quickly after hardware failure or accidental deletion • Version control - Roll back to known working configuration after unsuccessful changes • System migration - Transfer settings to replacement HMI or duplicate system with minimal downtime'),

('11111111-1111-1111-1111-111111111111', 29, 'Explain the importance of HMI touch screen maintenance.', 'PERFORMANCE: Regular cleaning prevents false touches, calibration ensures accurate registration, responsive interface reduces operator frustration. EXTENDED LIFESPAN: Preventive maintenance checks cables, avoids excessive pressure, controls temperature, delays costly replacements. REDUCED DOWNTIME: Scheduled maintenance identifies potential issues early, proactive replacement of worn components prevents unplanned stoppages.'),

-- SENSOR AND TRANSDUCER CARDS
('22222222-2222-2222-2222-222222222222', 16, 'Define a sensor and state its purpose in automation.', 'A device that detects or measures a physical property (light, temperature, position, pressure) and produces an output signal, usually electrical. Purpose in automation: Provides real-time feedback about process conditions to enable closed-loop control and enable monitoring of system state.'),

('22222222-2222-2222-2222-222222222222', 17, 'Explain optical encoder operation - incremental vs absolute types.', 'INCREMENTAL: Single track with slots. Each slot produces one pulse. Count pulses from reference point. Cannot determine position on power-up. Good for speed measurement. ABSOLUTE: Multiple concentric tracks with binary code. Each position unique. Read binary directly. Knows position immediately after power-up. Higher cost but more reliable.'),

('22222222-2222-2222-2222-222222222222', 18, 'Describe a thermocouple temperature sensor and its operating principle.', 'Seebeck Effect: When two dissimilar metals join, temperature difference generates voltage. Construction: Two metal wires (Chromel-Alumel) joined at measurement point. Output: Small voltage (0-50 mV) proportional to temperature difference. Advantages: Simple, robust, wide range. Disadvantages: Needs amplification, requires reference junction compensation.'),

('22222222-2222-2222-2222-222222222222', 19, 'Explain inductive proximity sensor operation.', 'Electromagnetic coil generates AC magnetic field. When metallic object approaches, eddy currents induced in metal. Eddy currents create opposing field, reducing oscillator amplitude. Amplitude drop detected, comparator triggers switch ON. Sensing distance: 2-20 mm. Response time: 1-5 ms. Advantage: Works through non-metallic barriers.'),

('22222222-2222-2222-2222-222222222222', 20, 'Describe LVDT sensor operation and demodulation process.', 'LVDT (Linear Variable Differential Transformer): Primary coil excited by AC voltage creates magnetic field. Core displaced moves field coupling to secondary coils. Series-opposing secondaries cancel when centered. Displacement changes voltage amplitude and polarity. Output: AC signal at excitation frequency, amplitude modulated by displacement. Demodulation: Synchronous rectifier recovers DC signal. Accuracy: ±0.1% possible.'),

('22222222-2222-2222-2222-222222222222', 21, 'What is a load cell and how does it measure force?', 'Transducer converting mechanical force to electrical signal. Metal body with internal strain gauges bonded to surface. Force deforms body elastically (micrometers). Deformation measured by strain gauges arranged in Wheatstone bridge. Bridge imbalance creates output voltage proportional to load. Output: Amplified to 4-20 mA or 0-10 V. Accuracy: ±0.1%. Applications: Scales, conveyor monitoring, assembly force feedback.'),

('22222222-2222-2222-2222-222222222222', 22, 'Describe seven major types of robot sensors with their principles.', '1. POTENTIOMETER: Resistance changes with rotation. Simple, low-cost, subject to wear. 2. OPTICAL ENCODER: Slots on disk detect light. Incremental (relative) or absolute (position). 3. ULTRASONIC: Emits sound, measures echo time. 2-4m range. 4. INFRARED: Emits IR, detects reflection. 1-30cm range. 5. FORCE/TORQUE: Strain gauges measure load. 6-axis measurement. 6. VISION CAMERA: Image recognition and tracking. 7. IMU: Accelerometer + gyroscope + magnetometer for orientation.'),

('22222222-2222-2222-2222-222222222222', 23, 'Explain humidity sensor operation - capacitive type.', 'Water molecules have high dielectric constant (~80). Polymer film between electrodes absorbs water molecules. Humidity changes dielectric constant, changing capacitance. Oscillator measures capacitance - frequency depends on capacitance. Higher humidity = higher capacitance = lower frequency. Electronics convert to voltage/current output. 4-20 mA or 0-10V typical. Accuracy: ±3-5%. Response: 15-60 seconds.'),

-- ROBOT TYPES AND CONFIGURATIONS
('11111111-1111-1111-1111-111111111111', 30, 'Describe four robotic configurations and their work envelopes.', 'SCARA: Two parallel rotary joints (X-Y) + linear vertical (Z). Cylindrical envelope. Fast, rigid vertically. SPHERICAL: Two rotary (base, shoulder) + linear arm. Spherical shell envelope. CYLINDRICAL: One rotary base + vertical linear + horizontal arm. Cylindrical envelope. CARTESIAN: Three orthogonal linear axes (X, Y, Z). Rectangular box envelope.'),

('11111111-1111-1111-1111-111111111111', 31, 'State and explain six major types of industrial robots.', '1. ARTICULATED: 6 rotary joints like human arm. High flexibility, dexterity. Welding, painting. 2. CARTESIAN: 3 linear axes perpendicular. Simple control, high precision. CNC, pick-place. 3. CYLINDRICAL: Rotary base + vertical/horizontal linear. Cylindrical envelope. Casting, coating. 4. SPHERICAL: 2 rotary + 1 linear. Spherical envelope. Early robots. 5. SCARA: 2 parallel rotary + 1 linear vertical. Fast, rigid. Assembly. 6. DELTA: 3 parallel arms, central platform. Very high speed. Packaging, food.'),

('11111111-1111-1111-1111-111111111111', 32, 'List the basic components of a robot and describe each function.', '1. MANIPULATOR (Arm): Links and joints provide mechanical structure and degrees of freedom. 2. END EFFECTOR: Gripper, suction cup, or tool interacts with environment. 3. ACTUATORS: Motors or hydraulic cylinders produce motion. 4. SENSORS: Position (encoder), force (load cell), distance (ultrasonic, IR). 5. CONTROLLER: PLC or microcontroller processes sensors, generates commands. 6. POWER SUPPLY: Electrical, pneumatic, or hydraulic energy source.'),

-- HYDRAULIC AND PNEUMATIC SYSTEMS
('22222222-2222-2222-2222-222222222222', 24, 'State the four fundamental components of a hydraulic system.',  '1. HYDRAULIC PUMP: Converts mechanical to hydraulic energy. Moves oil under pressure. 2. RESERVOIR: Stores fluid, allows settlement, dissipates heat. 3. CONTROL VALVES: Directional, pressure, flow control. Route fluid and regulate speed. 4. ACTUATOR: Cylinder (linear) or motor (rotary). Converts hydraulic to mechanical energy.'),

('22222222-2222-2222-2222-222222222222', 25, 'Compare and contrast hydraulic vs pneumatic systems - advantages and disadvantages.',  'HYDRAULIC: Incompressible fluid, 100-350 bar, high power density, smooth slow speed, 85-95% efficiency, excellent precision, expensive, leakage issues, safer high-pressure. PNEUMATIC: Compressible gas, 4-10 bar, lower power density, fast operation, 50-60% efficiency, simpler maintenance, inexpensive, poor efficiency, safer. TRADE-OFF: Hydraulic for power and precision, pneumatic for safety and cost.'),

('22222222-2222-2222-2222-222222222222', 26, 'Describe two types of pneumatic cylinders and compare characteristics.',  'SINGLE-ACTING: One air port. Spring returns piston. Advantages: Simple, low air use, fail-safe. Disadvantages: Limited stroke, weak return force, one-direction control. Applications: Clamping, ejection. DOUBLE-ACTING: Two air ports. Air pressure both directions. Advantages: Full stroke, force both ways, high speed control, heavy loads. Disadvantages: Complex valve, higher cost. Applications: Most industrial automation.'),

('22222222-2222-2222-2222-222222222222', 27, 'Explain pneumatic directional control valve operation and solenoid action.', 'Spool valve: Cylindrical sliding plunger with lands (sealing surfaces). Four ports: P (pressure), T (tank), A (work), B (work). Solenoid coil energization creates magnetic force, pulls plunger. Plunger movement shifts spool. Position 1: P→A, B→T (extend). Neutral: All blocked (hold). Position 2: P→B, A→T (retract). Spring returns to center when de-energized.'),

-- PLC OPERATION AND STRUCTURE
('11111111-1111-1111-1111-111111111111', 33, 'Define a PLC scan cycle and describe its five phases.', 'PLC scan cycle: Complete operation from reading inputs to writing outputs, executed continuously. INPUT SCAN: Read digital/analog inputs, store in image table (1-5 ms). PROGRAM EXECUTION: Solve ladder logic sequentially, update outputs (5-80 ms). OUTPUT SCAN: Write outputs to modules (1-5 ms). HOUSEKEEPING: Update timers, counters, diagnostics (1-3 ms). SCAN COMPLETION: Wait until cycle time expires. Total: 10-100 ms typically.'),

('11111111-1111-1111-1111-111111111111', 34, 'Explain how a PLC measures its own scan cycle time using timer methods.', 'Free-running 1ms timer counts elapsed time between scans. Ladder logic subtracts previous timer value from current value. Difference = scan time in milliseconds. Updates previous value for next cycle. Example: Current=1050ms, Previous=1000ms, ScanTime=50ms. Use 32-bit timer to avoid rollover. Result stored in memory for HMI display and diagnostics.'),

('11111111-1111-1111-1111-111111111111', 35, 'State and explain the basic block diagram of a PLC and its key components.', 'INPUT MODULES: Read field sensors, provide isolation, signal conditioning. CPU: Executes scan cycle - reads inputs, solves program, writes outputs. MEMORY: ROM (OS), RAM (program+data), Flash (program storage), Battery-backed RAM. POWER SUPPLY: Converts mains AC/DC to +5V, +24V DC. SYSTEM BUS: Internal communication between CPU, I/O, memory. OUTPUT MODULES: Convert logic to field signals. PROGRAMMING DEVICE: Develops, downloads, monitors program.'),

('11111111-1111-1111-1111-111111111111', 36, 'Describe the operation of PLC input modules and output modules.',  'INPUT MODULES: Sensor signal arrives at terminal. Optocoupler provides isolation (prevents noise). Threshold comparator converts to 5V logic (filtering prevents bounce). Logic signal stored in input image table during input scan. Used by all program rungs based on consistent snapshot. OUTPUT MODULES: CPU outputs 5V logic signal. Optocoupler isolates from field voltage. Power switch (transistor/triac) energizes field device (0.5-2A typical). Monitoring detects open circuit or short circuit faults.'),

('11111111-1111-1111-1111-111111111111', 37, 'Describe PLC components - Processor, Memory, Power Supply, and System Bus.', 'PROCESSOR: Brain of PLC. Executes scan cycle continuously. Reads inputs, solves logic, writes outputs. ALU performs arithmetic/logic. ~100MHz clock speed. MEMORY: ROM stores OS, RAM stores program + data, Flash survives power-loss, Battery-backed RAM retains values. Typical capacity: 10KB-2MB. POWER SUPPLY: Converts 110/230V AC or 24V DC to regulated 5V (CPU), 24V (I/O modules). Short-circuit protection, thermal shutdown, battery backup. SYSTEM BUS: Carries data, address, control, power signals. Enables communication between modules.'),

-- NETWORK AND COMMUNICATION
('22222222-2222-2222-2222-222222222222', 28, 'Define troubleshooting in networking and explain its systematic approach.', 'Troubleshooting: Systematic process identifying and resolving communication network problems. Steps: 1) Identify symptom (no link, slow data, packet loss) 2) Check physical layer (cables, power, link LED) 3) Check IP config (address, gateway, TCP/IP stack) 4) Ping gateway (local network) 5) Ping remote host (routing) 6) Ping hostname (DNS) 7) Test application (protocol specific). OSI layer-by-layer isolation from physical to application.'),

('22222222-2222-2222-2222-222222222222', 29, 'Describe Ethernet network troubleshooting steps - systematic flow.',  'STEP 1: Identify symptom (no link light, intermittent, slow). STEP 2: Check physical - verify cable seated, check LED, replace cable. STEP 3: Check IP - run ipconfig, verify subnet, ping localhost. STEP 4: Ping gateway - tests local network. If fails, check switch/VLAN. STEP 5: Ping remote by IP - tests routing. If fails, check routing/firewall. STEP 6: Ping hostname - tests DNS. If fails, check DNS server. STEP 7: Test application - check protocol ports. Systematic OSI layer isolation.'),

('11111111-1111-1111-1111-111111111111', 38, 'State four communication protocols used in industrial automation.', 'MODBUS: RS-232/485 or TCP/IP. PLC-to-HMI, device exchange. PROFINET: Industrial Ethernet. Real-time control data. ETHERNET/IP: Standard Ethernet + CIP. Control and information. PROFIBUS: Fieldbus serial protocol. Fast cyclic data exchange.'),

-- MODELING AND SIMULATION
('11111111-1111-1111-1111-111111111111', 39, 'Define system modeling and explain its importance in engineering design.',  'System modeling: Creating mathematical or logical representation capturing essential behaviors. Mathematical models (differential equations), Simulation models (executable code), Conceptual models (block diagrams). IMPORTANCE: Cost reduction (test before building), Performance prediction (determine specs), Control design (develop strategies), Risk mitigation (test safely), Education (understand behavior). Reduces prototyping, avoids failures, optimizes design.'),

('11111111-1111-1111-1111-111111111111', 40, 'Describe the system modeling procedure - 10 steps from problem to recommendations.',  'STEP 1: Define problem and objectives (what to model, what answers needed). STEP 2: Gather data and assumptions (physical parameters, constraints). STEP 3: Develop math model (apply physics laws, derive ODEs). STEP 4: Choose simulation tool (MATLAB, Python, LabVIEW). STEP 5: Implement model (build block diagram, code equations). STEP 6: Verify model (test analytical cases, debug). STEP 7: Validate model (compare to real system data). STEP 8: Run experiments (test scenarios, vary parameters). STEP 9: Analyze results (extract metrics, visualize). STEP 10: Document and recommend (report, design changes).'),

('11111111-1111-1111-1111-111111111111', 41, 'Compare and contrast verification and validation in system modeling.',  'VERIFICATION ("Are we building the model right?"): Confirms correct implementation. Tests against analytical solutions. Checks unit consistency. Numerical accuracy verification. Success: Output matches mathematical equations. VALIDATION ("Are we building the right model?"): Confirms accurate system representation. Compares to real measurements. Tests across operating range. Success: Output matches physical system (±5% typical). BOTH REQUIRED: Verification alone produces correct wrong equations. Validation alone accepts numerical errors. Typical sequence: Verify → Validate → Iterate if validation fails.'),

('11111111-1111-1111-1111-111111111111', 42, 'Define modeling and simulation and explain their integrated engineering role.',  'MODELING: Mathematical/logical representation of system capturing essential behaviors. From physics laws or data. SIMULATION: Running model over time to predict behavior under various conditions. Enables "what-if" testing. INTEGRATED: Model develops understanding. Simulation tests predictions. Used for: Control design (test strategies), Performance prediction (rise time, overshoot), Risk assessment (test failures), Product development (compare designs), Troubleshooting (diagnose problems). Reduces cost, increases speed, improves safety.'),

-- CONTROL THEORY
('11111111-1111-1111-1111-111111111111', 43, 'Explain PID control and the three correction terms - P, I, D.',  'PROPORTIONAL (Kp): Output proportional to current error. Fast response, reduces error quickly. But cannot eliminate steady-state error. Increased Kp increases overshoot. INTEGRAL (Ki): Accumulates error over time. Eliminates steady-state offset. Slow response. Increased Ki causes oscillation. DERIVATIVE (Kd): Measures rate of change, predicts future error. Reduces overshoot, smooths response. Sensitive to noise. COMBINED: Proportional fast response, Integral steady-state correction, Derivative smooth overshoot reduction.'),

('22222222-2222-2222-2222-222222222222', 30, 'Explain root locus method in control system design.',  'Graphical method showing closed-loop poles movement as gain varies 0→∞. PURPOSE: Design gain for desired pole locations, visualize stability changes, identify gain values for specific performance. OPERATION: Open-loop poles fixed. Closed-loop poles move as gain changes. Small K: poles near open-loop poles. Large K: poles toward open-loop zeros. DESIGN: Sketch root locus, select desired pole location, calculate required gain K. STABILITY: Poles left-half plane = stable. Right-half = unstable. INTERPRETATION: Pole real part = settling speed, Imaginary part = oscillation frequency.'),

('22222222-2222-2222-2222-222222222222', 31, 'Define Bode plot and explain gain/phase margins for stability.',  'BODE PLOT: Logarithmic frequency response showing magnitude (dB) and phase (degrees) vs frequency (rad/s). MAGNITUDE: 20 log₁₀|G(jω)| on dB scale. PHASE: Angle in degrees. GAIN MARGIN: How much gain can increase before instability. Measured at phase = -180°. Must be positive dB for stability. Typical requirement: > 6 dB (factor of 2). PHASE MARGIN: How much phase can lag before instability. Measured at magnitude = 0 dB crossing. Must be > 0° for stability. Typical requirement: > 45° for good response. STABILITY: Both margins positive = stable.'),

('11111111-1111-1111-1111-111111111111', 44, 'State Laplace Transform of common functions and derivatives.',  'δ(t)→1, u(t)→1/s, t→1/s², e^(-at)→1/(s+a), sin(ωt)→ω/(s²+ω²), cos(ωt)→s/(s²+ω²). DERIVATIVE: L{df/dt}=sF(s)-f(0). Multiplying by s = differentiation. INTEGRAL: L{∫f dt}=F(s)/s. Dividing by s = integration. LINEARITY: L{af+bg}=aF+bG. APPLICATION: Solve differential equations algebraically in frequency domain. Inverse transform back to time domain.'),

('22222222-2222-2222-2222-222222222222', 32, 'Explain significance of system poles and zeros in control design.',  'POLES: Roots of denominator. Control system stability and response. Real pole at s=-a contributes e^(-at) decay. Complex poles s=-σ±jω contribute e^(-σt)sin(ωt) damped oscillation. ZEROS: Roots of numerator. Affect frequency response and transient shape. Don''t appear in partial fraction decomposition. Zeros far from poles affect response. STABILITY: All poles left-half s-plane = stable. Right-half = unstable. DESIGN: Move poles leftward for faster response. Move away from imaginary axis for less overshoot.'),

('22222222-2222-2222-2222-222222222222', 33, 'Define Nyquist stability criterion and its application.',  'Criterion: Closed-loop stable if Nyquist plot encircles critical point (-1,0) counter-clockwise N times where N equals open-loop right-half poles. PLOT: Substitute s=jω in G(s)H(s), plot magnitude and phase on complex plane as ω varies 0→∞. INTERPRETATION: If plot does NOT encircle (-1,0) and open-loop stable, then closed-loop stable. If plot surrounds (-1,0), closed-loop unstable. MARGINS: Distance from plot to (-1,0) indicates gain/phase stability margin. ADVANTAGE: Handles transportation delay, any pole configuration. Works graphically without exact pole locations.'),

-- ADDITIONAL DETAILED CARDS (to reach 450+ total)
('11111111-1111-1111-1111-111111111111', 45, 'What is a pressure relief valve and explain its operation in hydraulic systems?', 'Safety device preventing system pressure exceeding safe maximum. COMPONENTS: Spring-loaded poppet, valve seat, adjustment screw, vent to reservoir. OPERATION: Below setpoint - spring holds poppet closed. At setpoint - hydraulic force equals spring force (equilibrium). Above setpoint - hydraulic force opens poppet, excess flow diverts to reservoir. System pressure drops, poppet reseats. FUNCTION: Protects components from overpressure, prevents seal rupture. ADJUSTMENT: Screw compresses/relaxes spring to change setpoint.'),

('22222222-2222-2222-2222-222222222222', 34, 'Explain modem operation - modulation and demodulation in industrial communication.',  'MODEM = Modulator + Demodulator. MODULATION (Digital to Analog): Converts binary bits to analog signal. Methods: Amplitude Shift Keying (ASK) - amplitude variation, Frequency Shift Keying (FSK) - frequency variation, Phase Shift Keying (PSK) - phase variation. DEMODULATION (Analog to Digital): Receives analog signal, filters noise, extracts modulation, recovers original bits. ERROR CORRECTION: Detects and corrects transmission errors. HISTORICAL: Essential for early remote industrial control. MODERN: Largely replaced by Ethernet, still used in cellular modems, IoT gateways.')

ON CONFLICT DO NOTHING;
